# Generated by Django 2.0.4 on 2018-08-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='exentas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='iva10',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='iva5',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_impuesto',
            field=models.CharField(choices=[('EXENTAS', 'Exentas'), ('IVA 10', 'Iva 10'), ('IVA 5', 'Iva 5')], default='IVA 10', max_length=20),
        ),
    ]
